language: node_js
node_js:
- '8'
env:
  global:
    # doubleface GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN> -r konnectors/cozy-konnector-facebook
    - secure: "kAu45Cgy+nnGck6rUqZrWwXhV+sdf8wTrYrcLkSDx/40eyLCOHPWwLYKcEaveIjaFqXR+LKsise1yeztHKmkrh8c48uTNqBnsWv7NsAHzg3O/rSW64J0HWo+yItJVbX7Cxz0v3RRorf5Jea0WPk8HF2zbcerJYHDNpqIMe7FAQiEzM4JOqb5bjQgrRuxeuMFT6QSQKVmzZp/bJnMQ8GLkH4Mi2m6213XYEt8strPdkn1u6j9b0vAKJSVbscOb+3Wo1f1PqKIDhhKo3h7KO27PZAzdGCJOwirn8yHeiLGwXXolytLRYpitFEuQRCeITbJXLUFtdEaAQbRb3lPDkOZJJXNNaRNlNafFpz0K/K/hqYQlKX8UeStS5rA13GIY1fAsLedHC0DkYSAhkxAakn2muy7dLAIsvVujmu0H0n8wcEKSik8Pd8XAg/taMev3jpSkHoulfMtbK/Utvwtj6vFkrZOV2sh7AjVkBq3cxO+odNEs4iJ4EFHlQDXzCOg/QgkO+3/w29BvbpTP2PT9n9TcJcCtJo0Y/1rOYvvcvRhUibgaKRCYXVO4BmxiJw1KGnwp7vObnJ2RyfJwgfbeXpO+Ej76Vqm2ewHUBD/2XbyFhzv0PJ3HE+w1iGyVLQgNYmrFmmot8uQPy1EHnrwaCZYg1HGTrA6I8TrCxk5D+sWr4o="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  - provider: script
    repo: $TRAVIS_REPO_SLUG
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: $TRAVIS_REPO_SLUG
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest yarn deploy
    on:
      branch: prod
